version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: homestead
    ports:
      - 3306:3306
    networks:
      mysql-local:
         ipv4_address: 10.5.0.2

networks:
  mysql-local:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      config:
      - subnet: 10.5.0.0/24
